# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-14 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_auto_20191110_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_clinic',
            name='ip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor_clinic',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor_clinic',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='ip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mdeical_transform',
            name='ip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='mdeical_transform',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mdeical_transform',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medical_script',
            name='ip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='medical_script',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medical_script',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='midicine',
            name='ip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='midicine',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='midicine',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='retired_pationt',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retired_pationt',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='working_pationt',
            name='ip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='working_pationt',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='working_pationt',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
