# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-17 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_auto_20191117_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdeical_transform2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120, verbose_name='اسم المريض ')),
                ('medical_number', models.CharField(max_length=120, verbose_name='الرقم الطبى ')),
                ('auth_doc', models.CharField(choices=[('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب العيادة ')),
                ('rcvd_service', models.CharField(blank=True, max_length=120, null=True, verbose_name='نوع الرعاية الطبية ')),
                ('followed_clinic', models.CharField(choices=[('جاردن سيتى', 'جاردن سيتى'), ('الفوالة', 'الفوالة'), ('المهندسيين', 'المهندسيين')], max_length=120, verbose_name=' ')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=120, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_clinic', models.ForeignKey(choices=[('جاردن سيتى', 'جاردن سيتى'), ('الفوالة', 'الفوالة'), ('المهندسيين', 'المهندسيين')], max_length=120, on_delete=django.db.models.deletion.CASCADE, to='app1.doctor_clinic', verbose_name=' اختر العيادة خارجية')),
                ('to_hospital', models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='app1.hospital', verbose_name=' اختر المستشفى')),
                ('to_lab', models.ForeignKey(choices=[('جاردن سيتى', 'جاردن سيتى'), ('الفوالة', 'الفوالة'), ('المهندسيين', 'المهندسيين')], max_length=120, on_delete=django.db.models.deletion.CASCADE, to='app1.laboratory', verbose_name='اختر المعمل او مركز الاشعة  ')),
            ],
        ),
        migrations.RenameModel(
            old_name='mdeical_transform',
            new_name='mdeical_transform1',
        ),
    ]
