# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20191117_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdeical_transform1',
            name='date_of_op',
            field=models.DateField(null=True, verbose_name='التاريخ  '),
        ),
        migrations.AddField(
            model_name='mdeical_transform2',
            name='date_of_op',
            field=models.DateField(null=True, verbose_name='التاريخ  '),
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='date_of_op',
            field=models.DateField(null=True, verbose_name='التاريخ  '),
        ),
        migrations.AddField(
            model_name='medical_script2',
            name='date_of_op',
            field=models.DateField(null=True, verbose_name='التاريخ  '),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='date_of_op',
            field=models.DateField(null=True, verbose_name='التاريخ  '),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='date_of_op',
            field=models.DateField(null=True, verbose_name='التاريخ  '),
        ),
        migrations.AlterField(
            model_name='mdeical_transform1',
            name='followed_clinic',
            field=models.CharField(choices=[('جاردن سيتى', 'جاردن سيتى'), ('الفوالة', 'الفوالة'), ('المهندسيين', 'المهندسيين')], max_length=120, verbose_name='العيادة التابعة '),
        ),
    ]
