# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-06 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20191118_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_accesspoint',
            name='floor',
            field=models.CharField(blank=True, choices=[('التاسع', 'التاسع'), ('الثامن', 'الثامن'), ('العاشر', 'العاشر'), ('السابع', 'السابع'), ('السادس', 'السادس'), ('الرابع', 'الرابع'), ('الحادى عشر', 'الحادى عشر'), ('الاول', 'الاول')], max_length=120, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AlterField(
            model_name='asset_blueprint',
            name='floor',
            field=models.CharField(blank=True, choices=[('التاسع', 'التاسع'), ('الثامن', 'الثامن'), ('العاشر', 'العاشر'), ('السابع', 'السابع'), ('السادس', 'السادس'), ('الرابع', 'الرابع'), ('الحادى عشر', 'الحادى عشر'), ('الاول', 'الاول')], max_length=120, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AlterField(
            model_name='asset_device',
            name='floor',
            field=models.CharField(blank=True, choices=[('التاسع', 'التاسع'), ('الثامن', 'الثامن'), ('العاشر', 'العاشر'), ('السابع', 'السابع'), ('السادس', 'السادس'), ('الرابع', 'الرابع'), ('الحادى عشر', 'الحادى عشر'), ('الاول', 'الاول')], max_length=120, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AlterField(
            model_name='asset_rack',
            name='floor',
            field=models.CharField(blank=True, choices=[('التاسع', 'التاسع'), ('الثامن', 'الثامن'), ('العاشر', 'العاشر'), ('السابع', 'السابع'), ('السادس', 'السادس'), ('الرابع', 'الرابع'), ('الحادى عشر', 'الحادى عشر'), ('الاول', 'الاول')], max_length=120, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AlterField(
            model_name='asset_repeater',
            name='floor',
            field=models.CharField(blank=True, choices=[('التاسع', 'التاسع'), ('الثامن', 'الثامن'), ('العاشر', 'العاشر'), ('السابع', 'السابع'), ('السادس', 'السادس'), ('الرابع', 'الرابع'), ('الحادى عشر', 'الحادى عشر'), ('الاول', 'الاول')], max_length=120, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AlterField(
            model_name='asset_router',
            name='floor',
            field=models.CharField(blank=True, choices=[('التاسع', 'التاسع'), ('الثامن', 'الثامن'), ('العاشر', 'العاشر'), ('السابع', 'السابع'), ('السادس', 'السادس'), ('الرابع', 'الرابع'), ('الحادى عشر', 'الحادى عشر'), ('الاول', 'الاول')], max_length=120, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AlterField(
            model_name='asset_server',
            name='floor',
            field=models.CharField(blank=True, choices=[('التاسع', 'التاسع'), ('الثامن', 'الثامن'), ('العاشر', 'العاشر'), ('السابع', 'السابع'), ('السادس', 'السادس'), ('الرابع', 'الرابع'), ('الحادى عشر', 'الحادى عشر'), ('الاول', 'الاول')], max_length=120, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AlterField(
            model_name='asset_stick',
            name='floor',
            field=models.CharField(blank=True, choices=[('التاسع', 'التاسع'), ('الثامن', 'الثامن'), ('العاشر', 'العاشر'), ('السابع', 'السابع'), ('السادس', 'السادس'), ('الرابع', 'الرابع'), ('الحادى عشر', 'الحادى عشر'), ('الاول', 'الاول')], max_length=120, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AlterField(
            model_name='asset_switch',
            name='floor',
            field=models.CharField(blank=True, choices=[('التاسع', 'التاسع'), ('الثامن', 'الثامن'), ('العاشر', 'العاشر'), ('السابع', 'السابع'), ('السادس', 'السادس'), ('الرابع', 'الرابع'), ('الحادى عشر', 'الحادى عشر'), ('الاول', 'الاول')], max_length=120, null=True, verbose_name='رقم الطابق'),
        ),
    ]
