# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-10 22:56
from __future__ import unicode_literals

import app1.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0008_auto_20200206_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='mgmt_board_membr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120, verbose_name='اسم المريض ')),
                ('job_title', models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية')),
                ('patient_age', models.CharField(max_length=120, verbose_name='سن المريض ')),
                ('medical_number', models.CharField(max_length=120, verbose_name=' الرقم الطبى ')),
                ('notes_number', models.CharField(max_length=120, verbose_name='رقم الدفتر ')),
                ('followed_clinic', models.CharField(choices=[('جاردن سيتى', 'جاردن سيتى'), ('الفوالة', 'الفوالة'), ('المهندسيين', 'المهندسيين')], max_length=120, verbose_name='العيادة التابعة')),
                ('the_image_file', models.FileField(blank=True, null=True, upload_to=app1.models.get_file_path01, verbose_name='صورة الطلب المرفق')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='retired_pationt',
            name='job_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name=' الدرجة الوظيفية عند المعاش'),
        ),
        migrations.AddField(
            model_name='retired_pationt',
            name='the_image_file',
            field=models.FileField(blank=True, null=True, upload_to=app1.models.get_file_path02, verbose_name='صورة الطلب المرفق'),
        ),
        migrations.AddField(
            model_name='working_pationt',
            name='job_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية'),
        ),
        migrations.AddField(
            model_name='working_pationt',
            name='the_image_file',
            field=models.FileField(blank=True, null=True, upload_to=app1.models.get_file_path01, verbose_name='صورة الطلب المرفق'),
        ),
    ]
