# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-19 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_mdeical_transform3_monthly_medical_script3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='auth_doc',
            field=models.CharField(choices=[('mohamed', 'mohamed'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب العيادة '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic10_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='10 علاج '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic11_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='11  علاج'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic12_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 12  '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic13_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='13 علاج '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic14_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 14  '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic15_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 15'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic16_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='16 علاج '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic17_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='17 علاج '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic18_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='18  علاج'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic19_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 19  '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic1_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 1'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic20_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='20 علاج '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic2_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='2 علاج '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic3_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='3 علاج '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic4_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='4  علاج'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic5_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 5  '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic6_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='6 علاج '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic7_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 7  '),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic8_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 8'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic9_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='9 علاج '),
        ),
    ]
