# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-20 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0012_auto_20200519_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_script3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120, verbose_name='اسم المريض ')),
                ('medical_number', models.CharField(max_length=120, verbose_name='الرقم الطبى ')),
                ('auth_doc', models.CharField(choices=[('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب العيادة ')),
                ('date_of_op', models.DateField(null=True, verbose_name='التاريخ  ')),
                ('medic1_name', models.CharField(max_length=120, verbose_name='علاج 1')),
                ('medic2_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='2 علاج ')),
                ('medic3_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='3 علاج ')),
                ('medic4_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='4  علاج')),
                ('medic5_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 5  ')),
                ('medic6_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='6 علاج ')),
                ('medic7_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 7  ')),
                ('medic1_cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 1')),
                ('medic2_cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 2')),
                ('medic3_cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 3')),
                ('medic4_cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 4')),
                ('medic5_cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 5')),
                ('medic6_cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 6')),
                ('medic7_cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 7')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=120, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='medic1_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='medic2_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='medic3_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='medic4_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='medic5_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='medic6_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='medic7_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AddField(
            model_name='medical_script2',
            name='medic1_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AddField(
            model_name='medical_script2',
            name='medic2_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AddField(
            model_name='medical_script2',
            name='medic3_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AddField(
            model_name='medical_script2',
            name='medic4_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AddField(
            model_name='medical_script2',
            name='medic5_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AddField(
            model_name='medical_script2',
            name='medic6_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AddField(
            model_name='medical_script2',
            name='medic7_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic2_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='2 علاج '),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic3_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='3 علاج '),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic4_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='4  علاج'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic5_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 5  '),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic6_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='6 علاج '),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic7_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 7  '),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic2_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='2 علاج '),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic3_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='3 علاج '),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic4_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='4  علاج'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic5_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 5  '),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic6_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='6 علاج '),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic7_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='علاج 7  '),
        ),
    ]
