# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20200520_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='searching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=120, verbose_name='الپحث پاسم الموظف')),
            ],
        ),
        migrations.AddField(
            model_name='mdeical_transform1',
            name='cost_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mdeical_transform1',
            name='transform_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة التحويل الطبى'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic10_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 10'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic11_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 11'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic12_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 12'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic13_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 13'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic14_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 14'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic15_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 15'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic16_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 16'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic17_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 17'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic18_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 18'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic19_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 19'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic20_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 20'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic8_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 8'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='medic9_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 9'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='cost_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic10_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 10'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic11_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 11'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic12_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 12'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic13_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 13'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic14_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 14'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic15_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 15'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic16_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 16'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic17_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 17'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic18_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 18'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic19_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 19'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic20_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 20'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic8_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 8'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='medic9_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 9'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='cost_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic10_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 10'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic11_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 11'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic12_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 12'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic13_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 13'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic14_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 14'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic15_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 15'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic16_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 16'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic17_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 17'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic18_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 18'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic19_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 19'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic20_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 20'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic8_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 8'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='medic9_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 9'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
    ]
