# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20200522_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_script1',
            name='updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='updater',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى'),
        ),
        migrations.AlterField(
            model_name='mdeical_transform1',
            name='auth_doc',
            field=models.CharField(choices=[('محمد', 'محمد'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب العيادة '),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='auth_doc',
            field=models.CharField(choices=[('محمد', 'محمد'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب العيادة '),
        ),
    ]
