# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-25 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20200524_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdeical_transform1',
            name='updater',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى'),
        ),
        migrations.AddField(
            model_name='mdeical_transform2',
            name='updater',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى'),
        ),
        migrations.AddField(
            model_name='mdeical_transform3',
            name='cost_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mdeical_transform3',
            name='updater',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى'),
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='cost_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medical_script1',
            name='total_medic_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='إجمالى التكاليف   '),
        ),
        migrations.AddField(
            model_name='medical_script2',
            name='cost_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medical_script2',
            name='updater',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى'),
        ),
        migrations.AddField(
            model_name='medical_script3',
            name='cost_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medical_script3',
            name='updater',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='cost_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='updater',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='updater',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='updater',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى'),
        ),
        migrations.AlterField(
            model_name='mdeical_transform1',
            name='cost_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='cost_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='cost_flag',
            field=models.BooleanField(default=False),
        ),
    ]
