# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-25 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20200525_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midicine',
            name='midicine_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='السعر'),
        ),
    ]
