# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20200525_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdeical_transform1',
            name='date_of_op',
        ),
        migrations.RemoveField(
            model_name='mdeical_transform2',
            name='date_of_op',
        ),
        migrations.RemoveField(
            model_name='mdeical_transform3',
            name='date_of_op',
        ),
        migrations.RemoveField(
            model_name='monthly_medical_script1',
            name='date_of_op',
        ),
        migrations.RemoveField(
            model_name='monthly_medical_script2',
            name='date_of_op',
        ),
        migrations.RemoveField(
            model_name='monthly_medical_script3',
            name='date_of_op',
        ),
        migrations.AddField(
            model_name='mdeical_transform1',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية'),
        ),
        migrations.AddField(
            model_name='mdeical_transform2',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية'),
        ),
        migrations.AddField(
            model_name='mdeical_transform3',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script2',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية'),
        ),
        migrations.AddField(
            model_name='monthly_medical_script3',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية'),
        ),
    ]
