# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-02 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20200529_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdeical_transform1',
            name='to_clinic',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='app1.doctor_clinic', verbose_name=' اختر العيادة خارجية'),
        ),
        migrations.AlterField(
            model_name='mdeical_transform1',
            name='to_lab',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='app1.laboratory', verbose_name='اختر المعمل او مركز الاشعة  '),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='auth_doc',
            field=models.CharField(choices=[('mohamed', 'mohamed'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب العيادة '),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='auth_doc',
            field=models.CharField(choices=[('mohamed', 'mohamed'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب العيادة '),
        ),
    ]
