# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-02 20:57
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20200602_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_script1',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='total_medic_cost',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='إجمالى التكاليف   '),
        ),
    ]
