# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-03 20:35
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20200602_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdeical_transform1',
            name='transform_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة التحويل الطبى'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AlterField(
            model_name='medical_script1',
            name='total_medic_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='إجمالى التكاليف   '),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AlterField(
            model_name='medical_script2',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AlterField(
            model_name='medical_script3',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic10_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 10'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic11_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 11'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic12_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 12'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic13_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 13'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic14_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 14'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic15_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 15'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic16_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 16'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic17_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 17'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic18_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 18'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic19_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 19'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic20_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 20'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic8_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 8'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script1',
            name='medic9_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 9'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic10_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 10'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic11_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 11'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic12_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 12'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic13_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 13'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic14_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 14'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic15_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 15'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic16_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 16'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic17_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 17'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic18_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 18'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic19_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 19'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic20_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 20'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic8_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 8'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script2',
            name='medic9_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 9'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic10_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 10'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic11_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 11'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic12_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 12'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic13_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 13'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic14_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 14'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic15_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 15'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic16_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 16'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic17_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 17'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic18_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 18'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic19_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 19'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic1_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 1'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic20_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 20'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic2_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 2'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic3_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 3'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic4_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 4'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic5_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 5'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic6_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 6'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic7_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 7'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic8_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 8'),
        ),
        migrations.AlterField(
            model_name='monthly_medical_script3',
            name='medic9_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True, verbose_name='تكلفة علاج رقم 9'),
        ),
    ]
