# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-03 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20200603_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdeical_transform1',
            name='to_clinic',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.doctor_clinic', verbose_name=' اختر العيادة خارجية'),
        ),
        migrations.AlterField(
            model_name='mdeical_transform1',
            name='to_hospital',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.hospital', verbose_name=' اختر المستشفى'),
        ),
        migrations.AlterField(
            model_name='mdeical_transform1',
            name='to_lab',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.laboratory', verbose_name='اختر المعمل او مركز الاشعة  '),
        ),
    ]
