# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-04 00:33
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20200604_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة علاج رقم 20'),
        ),
    ]
