# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-09 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_monthly_medical_script1_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='Added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mdeical_transform1',
            name='to_lab',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.laboratory', verbose_name='اختر المعمل   '),
        ),
    ]
