# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-09 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20200609_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
