# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-09 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_monthly_medical_script1_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_medical_script1',
            name='paper_code',
            field=models.CharField(default=uuid.uuid4, max_length=120),
        ),
    ]
