# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-10 10:39
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0030_searching_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='external_clinic_cure1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120, verbose_name='اسم المريض ')),
                ('medical_number', models.CharField(max_length=120, verbose_name='الرقم الطبى ')),
                ('auth_doc', models.CharField(choices=[('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب الشركة  ')),
                ('position', models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية')),
                ('cost_flag', models.BooleanField(default=False)),
                ('to_clinic', models.CharField(max_length=120, verbose_name=' اسم العيادة الخارجية')),
                ('rcvd_service', models.CharField(blank=True, max_length=120, null=True, verbose_name='نوع الرعاية الطبية المقدمة')),
                ('followed_clinic', models.CharField(choices=[('جاردن سيتى', 'جاردن سيتى'), ('الفوالة', 'الفوالة'), ('المهندسيين', 'المهندسيين')], max_length=120, verbose_name=' ')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=120, null=True)),
                ('updater', models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى')),
                ('check_cost', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة الكشف الطبى')),
                ('midicine_cost', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة  العلاج')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='external_clinic_cure2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120, verbose_name='اسم المريض ')),
                ('medical_number', models.CharField(max_length=120, verbose_name='الرقم الطبى ')),
                ('auth_doc', models.CharField(choices=[('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب الشركة  ')),
                ('position', models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية')),
                ('cost_flag', models.BooleanField(default=False)),
                ('to_clinic', models.CharField(max_length=120, verbose_name=' اسم العيادة الخارجية')),
                ('rcvd_service', models.CharField(blank=True, max_length=120, null=True, verbose_name='نوع الرعاية الطبية المقدمة')),
                ('followed_clinic', models.CharField(choices=[('جاردن سيتى', 'جاردن سيتى'), ('الفوالة', 'الفوالة'), ('المهندسيين', 'المهندسيين')], max_length=120, verbose_name=' ')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=120, null=True)),
                ('updater', models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى')),
                ('check_cost', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة الكشف الطبى')),
                ('midicine_cost', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة  العلاج')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='external_clinic_cure3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120, verbose_name='اسم المريض ')),
                ('medical_number', models.CharField(max_length=120, verbose_name='الرقم الطبى ')),
                ('auth_doc', models.CharField(choices=[('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب الشركة  ')),
                ('position', models.CharField(blank=True, max_length=120, null=True, verbose_name='الدرجة الوظيفية')),
                ('cost_flag', models.BooleanField(default=False)),
                ('to_clinic', models.CharField(max_length=120, verbose_name=' اسم العيادة الخارجية')),
                ('rcvd_service', models.CharField(blank=True, max_length=120, null=True, verbose_name='نوع الرعاية الطبية المقدمة')),
                ('followed_clinic', models.CharField(choices=[('جاردن سيتى', 'جاردن سيتى'), ('الفوالة', 'الفوالة'), ('المهندسيين', 'المهندسيين')], max_length=120, verbose_name=' ')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=120, null=True)),
                ('updater', models.CharField(blank=True, max_length=120, null=True, verbose_name='مستخدم المالى')),
                ('check_cost', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة الكشف الطبى')),
                ('midicine_cost', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=19, null=True, verbose_name='تكلفة  العلاج')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
