"""
Django settings for test1 project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q5rct0l#@tyx9fw!%m%*p*^#bh_k8sv&8i8mc6=m93k1==ps!j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['192.168.122.90','127.0.0.1','196.219.224.251','192.168.62.123','technical-support']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'registration',
    'smart_selects',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app1',
    'crispy_forms',
 #   'ajax_search',
    'multiselectfield'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

]

ROOT_URLCONF = 'test1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates"),os.path.join(BASE_DIR, "app1/templates/old/"),os.path.join(BASE_DIR, "app1/templates/master"),os.path.join(BASE_DIR, "app1/templates/master/doctor_clinic"),os.path.join(BASE_DIR, "app1/templates/master/monthly_script1"),os.path.join(BASE_DIR, "app1/templates/master/monthly_script2"),os.path.join(BASE_DIR, "app1/templates/master/monthly_script3"),os.path.join(BASE_DIR, "app1/templates/master/midicine"),os.path.join(BASE_DIR, "app1/templates/master/laboratory"),os.path.join(BASE_DIR, "app1/templates/master/hospital"),os.path.join(BASE_DIR, "app1/templates/master/working_pationt"),os.path.join(BASE_DIR, "app1/templates/master/retired_pationt"),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    
]




WSGI_APPLICATION = 'test1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Medical_Care',
        'USER': 'techadmin',
        'PASSWORD': 'pppppp',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {'charset':'utf8','read_default_file':'/etc/mysql/my.cnf' }

        
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_DJANGO_JQUERY = True

USE_L10N = True

USE_TZ = True

AJAX_SEARCH_LIMIT = 8

AJAX_SEARCH_HELPER = 'app.views.search_helper'

SEARCH_RESULT_TEMPLATE = 'search_results.html'

JQUERY_URL = True

SESSION_COOKIE_AGE = 100*600

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT =("/root/Desktop/test1")
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static_in_en","static_root")

STATICFILES_DIRS = [ os.path.join(BASE_DIR,"static")
,
'/home/osama/project/tech-v9/techapp/lib/python3.6/site-packages/django/contrib/admin/static'
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR),"media_root")

CRISPY_TEMPLATE_PACK = 'bootstrap4'
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_AUTO_LOGIN = True
SITE_ID =1


LOGIN_REDIRECT_URL=('main')
